export const sentencesA1 = {
    "Привет, как дела?": "Hello, how are you?",
    "Меня зовут Анна.": "My name is Anna.",
    "Я живу в Москве.": "I live in Moscow.",
    "Это мой друг.": "This is my friend.",
    "Я люблю читать книги.": "I like to read books.",
    "У меня есть собака.": "I have a dog.",
    "Сколько это стоит?": "How much is this?",
    "Где находится автобусная остановка?": "Where is the bus stop?",
    "Я учу английский язык.": "I am learning English.",
    "Пожалуйста, повторите.": "Please repeat.",
    "Как тебя зовут?": "What is your name?",
    "Мне нравится музыка.": "I like music.",
    "Она учительница.": "She is a teacher.",
    "Я хочу пить.": "I am thirsty.",
    "Я хочу есть.": "I am hungry.",
    "Это моя семья.": "This is my family.",
    "Он мой брат.": "He is my brother.",
    "У неё есть кошка.": "She has a cat.",
    "Сколько тебе лет?": "How old are you?",
    "Мне восемь лет.": "I am eight years old.",
    "Доброе утро!": "Good morning!",
    "Спокойной ночи!": "Good night!",
    "До свидания!": "Goodbye!",
    "Добро пожаловать!": "Welcome!",
    "Какой сегодня день?": "What day is it today?",
    "Сегодня понедельник.": "Today is Monday.",
    "Увидимся завтра.": "See you tomorrow.",
    "Где ты живёшь?": "Where do you live?",
    "Я живу в квартире.": "I live in an apartment.",
    "Ты голоден?": "Are you hungry?",
    "У меня есть брат и сестра.": "I have a brother and a sister.",
    "Мне холодно.": "I am cold.",
    "Мне жарко.": "I am hot.",
    "Это легко.": "It is easy.",
    "Это сложно.": "It is difficult.",
    "Я люблю спорт.": "I like sports.",
    "Он доктор.": "He is a doctor.",
    "Мне нравится учиться.": "I like to learn.",
    "Сегодня хороший день.": "It is a nice day today.",
    "Где твоя мама?": "Where is your mother?",
    "Моя мама на работе.": "My mother is at work.",
    "Я иду в школу.": "I am going to school.",
    "Ты говоришь по-английски?": "Do you speak English?",
    "Да, немного.": "Yes, a little.",
    "Нет, я не говорю.": "No, I do not speak.",
    "Моя любимая еда — пицца.": "My favorite food is pizza.",
    "Я люблю гулять.": "I like to walk.",
    "Пожалуйста, подожди меня.": "Please wait for me.",
    "Какое время сейчас?": "What time is it now?",
    "Сейчас три часа.": "It is three o'clock.",
    "Мне нужно идти домой.": "I need to go home.",
    "Я люблю смотреть фильмы.": "I like to watch movies.",
    "Ты хочешь мороженое?": "Do you want ice cream?",
    "Мой отец инженер.": "My father is an engineer.",
    "Я люблю шоколад.": "I love chocolate.",
    "У нас есть уроки сегодня?": "Do we have lessons today?",
    "Мне скучно.": "I am bored.",
    "Это интересно.": "It is interesting.",
    "Что ты делаешь?": "What are you doing?",
    "Я играю в футбол.": "I am playing football.",
    "Ты дома?": "Are you at home?",
    "Я смотрю телевизор.": "I am watching TV.",
    "Давай поиграем!": "Let's play!",
    "Ты можешь мне помочь?": "Can you help me?",
    "Конечно!": "Of course!",
    "Я боюсь.": "I am scared.",
    "Мне нравится лето.": "I like summer.",
    "Зима очень холодная.": "Winter is very cold.",
    "У меня новая книга.": "I have a new book.",
    "Какой твой любимый цвет?": "What is your favorite color?",
    "Мой любимый цвет — синий.": "My favorite color is blue.",
    "Ты умеешь плавать?": "Can you swim?",
    "Да, я умею плавать.": "Yes, I can swim.",
    "Я не могу найти свой телефон.": "I cannot find my phone.",
    "Он большой.": "It is big.",
    "Это маленький город.": "It is a small town.",
    "Пойдём в парк!": "Let's go to the park!",
    "Ты читаешь книгу?": "Are you reading a book?",
    "Я пишу письмо.": "I am writing a letter.",
    "Куда ты идёшь?": "Where are you going?",
    "Я еду на автобусе.": "I am taking the bus.",
    "Мне нравится бегать.": "I like to run.",
    "Сколько времени займёт поездка?": "How long will the trip take?",
    "Мы скоро приедем.": "We will arrive soon.",
    "Это мой дом.": "This is my house.",
    "Я люблю свою комнату.": "I love my room.",
    "У тебя есть карандаш?": "Do you have a pencil?",
    "Я потерял ключи.": "I lost my keys.",
    "Это новое платье.": "It is a new dress.",
    "Какой сегодня месяц?": "What month is it?",
    "Сейчас октябрь.": "It is October now.",
    "Я люблю цветы.": "I like flowers.",
    "Это моя машина.": "This is my car.",
    "Я иду в магазин.": "I am going to the shop.",
    "У меня день рождения завтра.": "It is my birthday tomorrow.",
    "Поздравляю!": "Congratulations!",
    "Ты готов?": "Are you ready?",
    "Да, я готов.": "Yes, I am ready.",
    "Пойдём домой.": "Let's go home.",
    "Я забыл твое имя.": "I forgot your name.",
    "Это моя любимая песня.": "This is my favorite song.",
    "Я устал.": "I am tired.",
    "Мой папа готовит ужин.": "My dad is cooking dinner.",
    "Я живу в большом доме.": "I live in a big house.",
    "Ты можешь открыть дверь?": "Can you open the door?",
    "У нас завтра тест.": "We have a test tomorrow."
};
