export const sentencesA2 = {
    "Я хотел бы забронировать номер в отеле.": "I would like to book a hotel room.",
    "Сколько времени займёт дорога до аэропорта?": "How long will it take to get to the airport?",
    "Мне нужно купить билеты на поезд.": "I need to buy train tickets.",
    "Можно мне посмотреть меню?": "Can I see the menu, please?",
    "В этом кафе очень вкусная еда.": "The food at this cafe is very delicious.",
    "Ты был когда-нибудь в другой стране?": "Have you ever been to another country?",
    "Как долго ты учишь английский?": "How long have you been learning English?",
    "Мне нужно пойти в супермаркет.": "I need to go to the supermarket.",
    "Я обычно встаю в семь утра.": "I usually get up at seven in the morning.",
    "Мы собираемся устроить вечеринку.": "We are going to have a party.",
    "Ты можешь помочь мне с домашним заданием?": "Can you help me with my homework?",
    "Я уже видел этот фильм раньше.": "I have already seen this movie before.",
    "Погода сегодня хуже, чем вчера.": "The weather today is worse than yesterday.",
    "Я часто хожу в спортзал по вечерам.": "I often go to the gym in the evenings.",
    "Какие у тебя планы на выходные?": "What are your plans for the weekend?",
    "Мы собираемся поехать в горы летом.": "We are going to the mountains in the summer.",
    "Ты когда-нибудь пробовал японскую еду?": "Have you ever tried Japanese food?",
    "Мой брат работает инженером.": "My brother works as an engineer.",
    "Я потерял свой кошелёк где-то здесь.": "I lost my wallet somewhere around here.",
    "Какой твой любимый предмет в школе?": "What is your favorite subject at school?",
    "Я помогу тебе помыть посуду.": "I will help you wash the dishes.",
    "Ты видел мои очки? Я их потерял.": "Have you seen my glasses? I lost them.",
    "Когда ты закончил университет?": "When did you finish university?",
    "Мне нравится ходить на пляж летом.": "I like to go to the beach in the summer.",
    "У меня нет времени готовить сегодня.": "I don’t have time to cook today.",
    "Он не умеет играть на гитаре.": "He cannot play the guitar.",
    "Мы смотрели очень интересный фильм вчера.": "We watched a very interesting movie yesterday.",
    "Я никогда не был в Лондоне.": "I have never been to London.",
    "Что ты хочешь на ужин сегодня?": "What do you want for dinner today?",
    "Она никогда не ест мясо.": "She never eats meat.",
    "Ты хочешь пойти в кино сегодня вечером?": "Do you want to go to the cinema tonight?",
    "Мне нужно одолжить у тебя ручку.": "I need to borrow a pen from you.",
    "Я изучаю английский, чтобы путешествовать.": "I study English to travel.",
    "Ты когда-нибудь летал на самолёте?": "Have you ever flown on a plane?",
    "Как часто ты ходишь в библиотеку?": "How often do you go to the library?",
    "Я встретил его три года назад.": "I met him three years ago.",
    "Ты хочешь присоединиться к нам на обед?": "Do you want to join us for lunch?",
    "Эта книга намного интереснее той.": "This book is much more interesting than that one.",
    "В моей комнате всегда чисто.": "My room is always clean.",
    "Она собирается начать новый проект.": "She is going to start a new project.",
    "Я не могу прийти на твою вечеринку.": "I can’t come to your party.",
    "Сегодня на улице очень холодно.": "It is very cold outside today.",
    "Что ты обычно делаешь по утрам?": "What do you usually do in the mornings?",
    "Я жду тебя на автобусной остановке.": "I am waiting for you at the bus stop.",
    "Ты можешь закрыть окно, пожалуйста?": "Can you close the window, please?",
    "Эта сумка слишком тяжёлая для меня.": "This bag is too heavy for me.",
    "Я только что вернулся домой.": "I have just come back home.",
    "Он хорошо говорит по-английски.": "He speaks English very well.",
    "Когда начинается твой рабочий день?": "When does your workday start?",
    "Мы скоро увидимся снова.": "We will see each other again soon.",
    "Я не могу решить эту задачу.": "I can’t solve this problem.",
    "Ты умеешь готовить пиццу?": "Can you cook pizza?",
    "Эта машина стоит очень дорого.": "This car costs a lot of money.",
    "Я люблю гулять в парке по вечерам.": "I like walking in the park in the evenings.",
    "Он был дома, когда я позвонил.": "He was at home when I called.",
    "Какой фильм ты хочешь посмотреть?": "Which movie do you want to watch?",
    "Я уже выпил три чашки кофе.": "I have already drunk three cups of coffee.",
    "Пожалуйста, скажи мне правду.": "Please tell me the truth.",
    "Они собираются купить новый дом.": "They are going to buy a new house.",
    "Я не слышал этого раньше.": "I have not heard this before.",
    "Когда ты вернёшься домой?": "When will you come back home?",
    "Ты хочешь помочь мне с проектом?": "Do you want to help me with the project?",
    "Я забыл выключить свет.": "I forgot to turn off the light.",
    "Эти цветы для тебя.": "These flowers are for you.",
    "Я работаю в большой компании.": "I work in a big company.",
    "Его родители живут в другом городе.": "His parents live in another city.",
    "Моя сестра изучает медицину.": "My sister is studying medicine.",
    "Она поедет в отпуск на следующей неделе.": "She will go on vacation next week.",
    "Ты можешь рассказать мне об этом?": "Can you tell me about it?",
    "Я не очень люблю зиму.": "I do not really like winter.",
    "Я часто забываю твой адрес.": "I often forget your address.",
    "Он всегда приносит обед из дома.": "He always brings lunch from home.",
    "Моя мама печёт вкусные пироги.": "My mother bakes delicious pies.",
    "Ты должен попробовать этот торт!": "You must try this cake!",
    "Я был на концерте вчера вечером.": "I was at the concert last night.",
    "Мы ходим на уроки танцев каждую субботу.": "We go to dance lessons every Saturday.",
    "Мне нравится, когда идёт снег.": "I like it when it snows.",
    "Ты можешь объяснить это ещё раз?": "Can you explain it again?",
    "Мой друг живёт в другой стране.": "My friend lives in another country.",
    "Я часто путешествую с друзьями.": "I often travel with my friends.",
    "Мы гуляли в парке весь день.": "We walked in the park all day.",
    "Я забыл купить молоко в магазине.": "I forgot to buy milk at the store.",
    "Ты можешь открыть дверь?": "Can you open the door?",
    "Я хотел бы посетить Францию.": "I would like to visit France.",
    "Скоро начнётся дождь.": "It will start raining soon.",
    "Мой дедушка любит читать газеты.": "My grandfather likes to read newspapers.",
    "Ты видел мои новые ботинки?": "Have you seen my new shoes?"
};
