export const sentencesB1 = {
    "Я планирую начать учить новый язык.": "I am planning to start learning a new language.",
    "Когда я был ребёнком, я мечтал стать пилотом.": "When I was a child, I dreamed of becoming a pilot.",
    "Ты когда-нибудь участвовал в соревнованиях?": "Have you ever taken part in a competition?",
    "Мне нужно разобраться, как это работает.": "I need to figure out how this works.",
    "Я хотел бы улучшить свои навыки общения.": "I would like to improve my communication skills.",
    "Мы обсуждали этот проект на последней встрече.": "We discussed this project at the last meeting.",
    "Я не могу решить, какое платье надеть на вечеринку.": "I can't decide which dress to wear to the party.",
    "Ты должен следовать инструкциям внимательно.": "You must follow the instructions carefully.",
    "Мой друг посоветовал мне прочитать эту книгу.": "My friend recommended that I read this book.",
    "Я забыл, где оставил ключи от машины.": "I forgot where I left my car keys.",
    "Он был удивлён, когда узнал новости.": "He was surprised when he heard the news.",
    "Вы когда-нибудь задумывались о смене работы?": "Have you ever thought about changing your job?",
    "Я чувствую себя уверенно, когда говорю по-английски.": "I feel confident when I speak English.",
    "Это самое красивое место, которое я когда-либо видел.": "This is the most beautiful place I have ever seen.",
    "Они решили переехать в другой город из-за работы.": "They decided to move to another city because of work.",
    "Я не уверен, что это хорошая идея.": "I am not sure that this is a good idea.",
    "Ты должен быть терпеливым, чтобы добиться успеха.": "You have to be patient to achieve success.",
    "Мы ещё не закончили этот проект.": "We have not finished this project yet.",
    "Если погода будет хорошей, мы поедем на пикник.": "If the weather is good, we will go for a picnic.",
    "Когда я закончу учёбу, я найду работу своей мечты.": "When I finish my studies, I will find my dream job.",
    "Этот фильм основан на реальной истории.": "This movie is based on a true story.",
    "Пожалуйста, убедись, что ты выключил свет перед уходом.": "Please make sure you turn off the lights before leaving.",
    "Я начал заниматься спортом, чтобы быть здоровым.": "I started exercising to stay healthy.",
    "Ты можешь объяснить, как решить эту задачу?": "Can you explain how to solve this problem?",
    "Он очень гордится своими достижениями.": "He is very proud of his achievements.",
    "Я всегда беру зонт, когда идёт дождь.": "I always take an umbrella when it rains.",
    "Ты когда-нибудь путешествовал один?": "Have you ever traveled alone?",
    "Мне нужно подготовиться к завтрашнему экзамену.": "I need to prepare for tomorrow's exam.",
    "Она хочет поступить в университет за границей.": "She wants to enter a university abroad.",
    "Я стараюсь избегать нездоровой пищи.": "I try to avoid unhealthy food.",
    "Ты мог бы мне помочь, если у тебя есть свободное время?": "Could you help me if you have some free time?",
    "Мой брат очень интересуется историей.": "My brother is very interested in history.",
    "Если ты не поторопишься, мы опоздаем на поезд.": "If you don’t hurry up, we will miss the train.",
    "Я бы хотел узнать больше о твоей культуре.": "I would like to learn more about your culture.",
    "Она сказала, что вернётся через час.": "She said she would come back in an hour.",
    "Мы поехали в музей, чтобы увидеть новую выставку.": "We went to the museum to see the new exhibition.",
    "Он всегда забывает делать домашнее задание.": "He always forgets to do his homework.",
    "Как только я закончу работу, я позвоню тебе.": "As soon as I finish work, I will call you.",
    "Я не привык вставать так рано по утрам.": "I am not used to getting up so early in the mornings.",
    "Я хотел бы научиться готовить итальянскую еду.": "I would like to learn how to cook Italian food.",
    "Почему ты опоздал на встречу сегодня утром?": "Why were you late for the meeting this morning?",
    "Мы решили остаться дома из-за плохой погоды.": "We decided to stay at home because of the bad weather.",
    "Если у тебя есть вопросы, не стесняйся спрашивать.": "If you have any questions, don't hesitate to ask.",
    "Этот фильм был слишком скучным для меня.": "This movie was too boring for me.",
    "Он всегда помогает своим друзьям, когда они нуждаются в помощи.": "He always helps his friends when they need help.",
    "У меня нет времени на хобби в будние дни.": "I don’t have time for hobbies on weekdays.",
    "Она привыкла пить кофе каждое утро.": "She is used to drinking coffee every morning.",
    "Если я найду твой телефон, я позвоню тебе.": "If I find your phone, I will call you.",
    "Ты уже решил, куда поедешь летом?": "Have you already decided where you will go this summer?",
    "Она сказала, что ей нужно больше времени на проект.": "She said that she needs more time for the project.",
    "Я никогда не был так счастлив в своей жизни.": "I have never been so happy in my life.",
    "Ты должен приложить усилия, если хочешь что-то изменить.": "You have to make an effort if you want to change something.",
    "Моя сестра выиграла соревнование по плаванию.": "My sister won the swimming competition.",
    "Ты когда-нибудь пользовался этим приложением?": "Have you ever used this app?",
    "Я не могу позволить себе купить новую машину сейчас.": "I can’t afford to buy a new car right now.",
    "Они ищут квартиру поближе к центру города.": "They are looking for an apartment closer to the city center.",
    "Почему ты не предупредил меня заранее?": "Why didn’t you warn me in advance?",
    "Этот ресторан предлагает лучшие блюда в городе.": "This restaurant offers the best dishes in town.",
    "Я никогда не забуду свой первый день в школе.": "I will never forget my first day at school.",
    "Моя цель — говорить по-английски свободно.": "My goal is to speak English fluently.",
    "Она не знала, как ответить на его вопрос.": "She didn’t know how to answer his question.",
    "Я собираюсь позвонить своему другу после работы.": "I am going to call my friend after work.",
    "Ты когда-нибудь писал письмо на английском языке?": "Have you ever written a letter in English?",
    "Мы провели весь день, изучая новую тему.": "We spent the whole day studying a new topic.",
    "Это решение повлияло на многих людей.": "This decision has affected many people.",
    "Я надеюсь, что в будущем всё будет лучше.": "I hope that everything will be better in the future.",
    "Ты должен быть внимательным на дорогах.": "You need to be careful on the roads.",
    "Мы не ожидали, что погода так испортится.": "We didn’t expect the weather to get so bad.",
    "Она начала новый бизнес несколько месяцев назад.": "She started a new business a few months ago.",
    "Ты можешь посоветовать мне хороший фильм?": "Can you recommend a good movie to me?"
};
