export const sentencesB2 = {
    "Я понял, что допустил ошибку, но уже было слишком поздно.": "I realized that I had made a mistake, but it was already too late.",
    "Если бы я знал об этом раньше, я бы смог помочь тебе.": "If I had known about it earlier, I could have helped you.",
    "Она не ожидала, что интервью будет таким сложным.": "She didn't expect the interview to be so difficult.",
    "Мы хотели бы обсудить этот вопрос до принятия решения.": "We would like to discuss this issue before making a decision.",
    "Хотя он устал, он продолжил работать над проектом.": "Although he was tired, he kept working on the project.",
    "Ты должен научиться справляться со стрессом на работе.": "You need to learn how to cope with stress at work.",
    "Это была одна из самых запоминающихся поездок в моей жизни.": "It was one of the most memorable trips of my life.",
    "Мне пришлось пересмотреть свои приоритеты из-за новой работы.": "I had to reconsider my priorities because of my new job.",
    "Он спросил, был ли я доволен результатами экзамена.": "He asked if I was satisfied with the exam results.",
    "Если бы они работали вместе, они бы закончили быстрее.": "If they had worked together, they would have finished faster.",
    "Нам следует подготовиться к встрече заранее.": "We should prepare for the meeting in advance.",
    "Я не уверен, что смогу присутствовать на вечеринке в пятницу.": "I’m not sure if I can attend the party on Friday.",
    "Этот документ содержит всю необходимую информацию.": "This document contains all the necessary information.",
    "Я был удивлён, когда узнал, что он выиграл соревнование.": "I was surprised to find out that he had won the competition.",
    "Она всегда находит способ решить даже самые сложные проблемы.": "She always finds a way to solve even the most difficult problems.",
    "Ты когда-нибудь задумывался о том, чтобы переехать в другой город?": "Have you ever considered moving to another city?",
    "Он признал, что не смог справиться с задачей вовремя.": "He admitted that he couldn’t complete the task on time.",
    "Мы могли бы пойти в кино, если ты не занят сегодня вечером.": "We could go to the cinema if you’re not busy tonight.",
    "Ты должен учитывать последствия своих решений.": "You need to take the consequences of your decisions into account.",
    "Я рекомендую тебе сделать небольшой перерыв и отдохнуть.": "I recommend that you take a short break and relax.",
    "Хотя погода была ужасной, они решили пойти на прогулку.": "Although the weather was terrible, they decided to go for a walk.",
    "Если ты продолжишь так работать, ты быстро достигнешь успеха.": "If you keep working like this, you will achieve success quickly.",
    "Я не могу позволить себе терять время на ненужные встречи.": "I can’t afford to waste time on unnecessary meetings.",
    "Он объяснил, почему решил сменить работу в последний момент.": "He explained why he decided to change jobs at the last moment.",
    "Она сказала, что не хочет обсуждать эту тему сейчас.": "She said that she didn’t want to discuss this topic right now.",
    "Они столкнулись с несколькими трудностями на пути к успеху.": "They encountered several difficulties on their way to success.",
    "Я ожидал, что он придёт вовремя, но он снова опоздал.": "I expected him to arrive on time, but he was late again.",
    "Ты можешь объяснить мне, как использовать эту программу?": "Can you explain to me how to use this software?",
    "Если бы я знал о проблеме, я бы помог тебе сразу.": "If I had known about the problem, I would have helped you immediately.",
    "Она всегда настаивает на том, чтобы всё было сделано идеально.": "She always insists on everything being done perfectly.",
    "Несмотря на нехватку времени, мы всё равно закончили проект вовремя.": "Despite the lack of time, we still finished the project on time.",
    "Мы собираемся рассмотреть твои предложения на следующей встрече.": "We are going to consider your suggestions at the next meeting.",
    "Ты должен быть готов к неожиданным изменениям в планах.": "You need to be prepared for unexpected changes in plans.",
    "Я был настолько увлечён книгой, что прочитал её за один день.": "I was so absorbed in the book that I read it in one day.",
    "Если ты продолжишь учиться, твой английский значительно улучшится.": "If you keep studying, your English will improve significantly.",
    "Она упомянула, что собирается уехать за границу на несколько месяцев.": "She mentioned that she was going to go abroad for a few months.",
    "Мы должны сосредоточиться на том, что действительно важно.": "We must focus on what really matters.",
    "Они предложили обсудить проблему на следующей неделе.": "They suggested discussing the problem next week.",
    "Я не могу вспомнить, где видел этот фильм раньше.": "I can’t remember where I saw this movie before.",
    "Он гордится тем, что достиг такого высокого уровня в карьере.": "He is proud of having reached such a high level in his career.",
    "Ты мог бы дать мне совет, как решить эту проблему?": "Could you give me some advice on how to solve this problem?",
    "Это была трудная ситуация, но мы справились с ней вместе.": "It was a difficult situation, but we dealt with it together.",
    "Несмотря на усталость, она продолжала усердно работать.": "Despite feeling tired, she continued working hard.",
    "Я уверен, что мы найдём выход из этой ситуации.": "I am sure that we will find a way out of this situation.",
    "Если бы я знал больше, я бы принял другое решение.": "If I had known more, I would have made a different decision.",
    "Он сказал, что никогда не был в таком красивом месте.": "He said that he had never been to such a beautiful place.",
    "Ты должен учиться на своих ошибках, чтобы стать лучше.": "You need to learn from your mistakes to become better.",
    "Мы приняли участие в конференции, чтобы узнать новые идеи.": "We attended the conference to learn new ideas.",
    "Она уверена, что сможет справиться со всеми задачами.": "She is confident that she can handle all the tasks.",
    "Я не ожидал, что презентация займёт так много времени.": "I didn’t expect the presentation to take so much time.",
    "Он объяснил, почему решил отказаться от предложения.": "He explained why he had decided to decline the offer.",
    "Если бы у меня был выбор, я бы предпочёл работать из дома.": "If I had the choice, I would prefer to work from home."
};
